import assert from 'node:assert/strict';
import fs from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {apply,newSave} from '../src/game.mjs';
import {RARITIES,SPECIES,PACKS,parseCard} from '../public/data.mjs';
import worker from '../dist/server/index.js';
const seq=(...values)=>()=>values.length?values.shift():.1;
assert.equal(SPECIES.length,48);assert.equal(new Set(SPECIES.map(s=>s.name)).size,48);assert.equal(RARITIES.reduce((s,x)=>s+x.weight,0),100);assert.equal(SPECIES.length*RARITIES.length,288);
let s=newSave();s.profiles[0].coins=10000;s.profiles[0].pity=19;let result=apply(s,0,'pack',{pack:'forest'},()=>.1);assert.equal(result.cards.length,5);assert.equal(parseCard(result.cards[4].key).tier,4);assert.equal(s.profiles[0].pity,0);assert(result.cards.every(c=>parseCard(c.key).species.region===0));assert.equal(s.profiles[0].coins,9680);
s=newSave();s.profiles[0].coins=1000;result=apply(s,0,'pack',{pack:'celestial'},()=>0);assert(parseCard(result.cards[4].key).tier>=2);const before=s.profiles[0].coins;assert.throws(()=>apply(s,0,'pack',{pack:'celestial'}));assert.equal(s.profiles[0].coins,before);
s=newSave();apply(s,0,'pack',{pack:'wild'},()=>0);assert.equal(s.profiles[0].cards['0-0'],5);assert.deepEqual(apply(s,0,'recycle'),{gained:12,count:4});assert.equal(s.profiles[0].cards['0-0'],1);assert.throws(()=>apply(s,0,'recycle'));assert.throws(()=>apply(s,0,'craft',{key:'1-0'}));s.profiles[0].dust=30;apply(s,0,'craft',{key:'1-0'});assert.equal(s.profiles[0].dust,0);assert.throws(()=>apply(s,0,'craft',{key:'1-0'}));apply(s,0,'claim',{mission:'first'});assert.throws(()=>apply(s,0,'claim',{mission:'first'}));
for(const kind of ['timing','memory','sort']){s=newSave();const session=apply(s,0,'startGame',{game:kind},()=>.5,1000);let data={id:session.id};if(kind==='timing')data.hits=[100,100,100,100,100,100];if(kind==='sort')data.answers=Array.from({length:20},(_,i)=>(session.seed*13+i*7+Math.floor(i/3))%4);if(kind==='memory'){data.moves=[];for(let i=0;i<6;i++)data.moves.push(session.board.map((v,n)=>v===i?n:-1).filter(v=>v>=0));}const r=apply(s,0,'finishGame',data,()=>.5,40000);assert.equal(r.reward,kind==='memory'?400:480);assert.equal(s.profiles[0].coins,600+r.reward);assert.throws(()=>apply(s,0,'finishGame',data,()=>.5,40001));}
const sqlite=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(x=>x.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+f,'utf8'));
const DB={prepare(query){let params=[];return {bind(...args){params=args;return this;},async first(){return sqlite.prepare(query).get(...params)||null;},async run(){const r=sqlite.prepare(query).run(...params);return {meta:{changes:r.changes}};}}}};
let n=0;async function req(owner,path,body){const h={'Content-Type':'application/json'};if(owner)h['oai-authenticated-user-id']=owner;const r=await worker.fetch(new Request('https://lumen.test'+path,{method:body?'POST':'GET',headers:h,body:body?JSON.stringify(body):undefined}),{DB});return {status:r.status,body:await r.json()};}
async function act(owner,kind,data={},id='test-action-'+(++n)){return req(owner,'/api/action',{profile:0,kind,data,id});}
assert.equal((await req(null,'/api/state')).status,401);
const emailRequest=()=>new Request('https://lumen.test/api/state',{headers:{'oai-authenticated-user-email':'Collector@Example.com'}});
const emailResult=await worker.fetch(emailRequest(),{DB});assert.equal(emailResult.status,200);assert.equal((await emailResult.json()).state.profiles[0].coins,600);
const invalidEmail=await worker.fetch(new Request('https://lumen.test/api/state',{headers:{'oai-authenticated-user-email':'not-an-email'}}),{DB});assert.equal(invalidEmail.status,401);
await req('alice','/api/state');await req('bob','/api/state');await req('mallory','/api/state');
let a=await act('alice','pack',{pack:'wild'},'idempotent-123');assert.equal(a.body.state.profiles[0].coins,360);let a2=await act('alice','pack',{pack:'wild'},'idempotent-123');assert.equal(a2.body.state.profiles[0].coins,360);assert.deepEqual(a.body.result,a2.body.result);assert.equal((await req('bob','/api/state')).body.state.profiles[0].coins,600);
const room=(await req('alice','/api/room',{op:'create'})).body.room;assert.equal(room.players[0].me,true);assert.equal(room.players[1],null);assert.equal((await act('alice','duelPack',{code:room.code})).status,400);const joined=await req('bob','/api/room',{op:'join',code:room.code});assert.equal(joined.status,200);assert.equal(joined.body.room.players[1].me,true);assert.equal((await req('mallory','/api/room?code='+room.code)).status,400);assert.equal((await req('mallory','/api/room',{op:'join',code:room.code})).status,400);
a=await act('alice','duelPack',{code:room.code});assert.equal(a.status,200);let v=(await req('bob','/api/room?code='+room.code)).body.room;assert.equal(v.players[0].rounds.length,1);assert.equal(v.players[1].rounds.length,0);assert(!JSON.stringify(v).includes('coins'));assert(!JSON.stringify(v).includes('alice'));
// A reward with the same id must be safe after a connection retry.
const start=await act('bob','startGame',{game:'timing'});const session=start.body.result;const row=sqlite.prepare('SELECT payload FROM lumen_saves WHERE owner=?').get('bob');const payload=JSON.parse(row.payload);payload.profiles[0].session.started-=5000;sqlite.prepare('UPDATE lumen_saves SET payload=? WHERE owner=?').run(JSON.stringify(payload),'bob');const rewardId='reward-'+session.id;const reward=await act('bob','finishGame',{id:session.id,hits:[100,100,100,100,100,100]},rewardId);const again=await act('bob','finishGame',{id:session.id,hits:[100,100,100,100,100,100]},rewardId);assert.equal(reward.body.state.profiles[0].coins,1080);assert.equal(again.body.state.profiles[0].coins,1080);
const badOrigin=await worker.fetch(new Request('https://lumen.test/api/action',{method:'POST',headers:{'oai-authenticated-user-id':'bob','Content-Type':'application/json','Origin':'https://evil.test'},body:'{}'}),{DB});assert.equal(badOrigin.status,403);
for(const path of ['/','/style.css','/app.mjs','/data.mjs','/assets/forest.webp','/assets/tide.webp','/assets/ember.webp']){const res=await worker.fetch(new Request('https://lumen.test'+path),{DB});assert.equal(res.status,200);assert((await res.arrayBuffer()).byteLength>0);}assert.equal((await worker.fetch(new Request('https://lumen.test/no-such-file'),{DB})).status,404);
console.log('PASS: 288 catalog entries, region pools, pity, premium guarantee, economy, recycling, crafting, missions, all minigame rewards, auth isolation, idempotent purchases/rewards, room membership, 2-player progression, CSRF, and all 7 site asset routes.');
