import {PACKS,RARITIES,MISSIONS,parseCard} from '../public/data.mjs';
export function profile(name){return {name,coins:600,dust:0,cards:{},pity:0,packs:0,games:0,earned:0,claimed:[],lastPack:null,session:null,duels:{},best:{timing:0,memory:0,sort:0}};}
export function newSave(){return {profiles:[profile('별빛 수집가')],receipts:[]};}
export function weighted(weights,rng){let roll=rng()*weights.reduce((a,b)=>a+b,0);for(let i=0;i<weights.length;i++){roll-=weights[i];if(roll<0)return i;}return weights.length-1;}
export function secureRandom(){const a=new Uint32Array(1);crypto.getRandomValues(a);return a[0]/4294967296;}
export function apply(state,pidx,kind,data={},rng=secureRandom,now=Date.now()){
if(pidx!==0)throw Error('플레이어를 선택해 주세요.');const p=state.profiles[pidx];let result={};
if(kind==='duelPack'){const code=data.code;if(!/^[A-Z0-9]{6}$/.test(code))throw Error('방 코드가 올바르지 않아요.');p.duels??={};const old=p.duels[code]||[];if(old.length>=5)throw Error('이 대결의 팩을 모두 개봉했어요.');const pack=apply(state,0,'pack',{pack:'wild'},rng,now);p.duels[code]=[...old,pack];return pack;}
if(kind==='pack'){const pack=PACKS.find(x=>x.id===data.pack);if(!pack)throw Error('없는 카드 팩이에요.');if(p.coins<pack.price)throw Error('코인이 부족해요. 미니게임에서 코인을 모아 보세요.');p.coins-=pack.price;p.packs++;p.pity++;const guaranteed=p.pity>=20,cards=[];for(let i=0;i<5;i++){let tier=weighted(RARITIES.map(r=>r.weight),rng);if(pack.id==='celestial'&&i===4)tier=weighted([0,0,70,22,7,1],rng);if(guaranteed&&i===4&&tier<4)tier=4;const species=pack.region===null?Math.floor(rng()*48):pack.region*16+Math.floor(rng()*16),key=`${species}-${tier}`,isNew=!p.cards[key];p.cards[key]=(p.cards[key]||0)+1;cards.push({key,isNew});}if(cards.some(c=>parseCard(c.key).tier>=4))p.pity=0;p.lastPack={id:crypto.randomUUID(),pack:pack.id,cards,at:now,guaranteed};result=p.lastPack;
}else if(kind==='recycle'){let gained=0,count=0;for(const [key,n]of Object.entries(p.cards)){if(n>1){gained+=(n-1)*RARITIES[parseCard(key).tier].dust;count+=n-1;p.cards[key]=1;}}if(!count)throw Error('재료로 바꿀 중복 카드가 없어요.');p.dust+=gained;result={gained,count};
}else if(kind==='craft'){const c=parseCard(data.key);if(!c)throw Error('없는 카드예요.');if(p.cards[c.key])throw Error('이미 보유한 카드예요.');if(p.dust<c.rarity.cost)throw Error('별가루가 부족해요.');p.dust-=c.rarity.cost;p.cards[c.key]=1;result={key:c.key};
}else if(kind==='claim'){const m=MISSIONS.find(x=>x.id===data.mission);if(!m||p.claimed.includes(m.id))throw Error('이미 받았거나 없는 목표예요.');const n=m.field==='unique'?Object.keys(p.cards).length:p[m.field];if(n<m.target)throw Error('아직 목표를 달성하지 못했어요.');p.claimed.push(m.id);p.coins+=m.reward;result={reward:m.reward};
}else if(kind==='rename'){const name=String(data.name||'').trim();if(!name||name.length>12)throw Error('이름을 1–12자로 입력해 주세요.');p.name=name;
}else if(kind==='startGame'){if(!['timing','memory','sort'].includes(data.game))throw Error('없는 미니게임이에요.');if(p.session&&now-p.session.started<1500)throw Error('잠시 후 다시 시작해 주세요.');const symbols=[0,1,2,3,4,5,0,1,2,3,4,5];for(let i=11;i>0;i--){const j=Math.floor(rng()*(i+1));[symbols[i],symbols[j]]=[symbols[j],symbols[i]];}p.session={id:crypto.randomUUID(),game:data.game,started:now,seed:Math.floor(rng()*1000000),board:symbols};result=p.session;
}else if(kind==='finishGame'){const s=p.session;if(!s||s.id!==data.id)throw Error('종료된 게임이에요. 새로 시작해 주세요.');const elapsed=now-s.started;if(elapsed<2000||elapsed>600000)throw Error('게임 시간이 유효하지 않아요. 새로 시작해 주세요.');let reward=0,score=0;
if(s.game==='timing'){if(!Array.isArray(data.hits)||data.hits.length!==6||data.hits.some(v=>!Number.isFinite(v)||v<0||v>100))throw Error('게임 결과를 확인할 수 없어요.');score=Math.round(data.hits.reduce((a,b)=>a+b,0)/6);reward=90+Math.round(score*3.9);}
if(s.game==='memory'){if(!Array.isArray(data.moves)||data.moves.length<6||data.moves.length>200)throw Error('게임 결과를 확인할 수 없어요.');const matched=new Set();for(const pair of data.moves){if(!Array.isArray(pair)||pair.length!==2||pair.some(i=>!Number.isInteger(i)||i<0||i>11)||pair[0]===pair[1]||pair.some(i=>matched.has(i)))throw Error('유효하지 않은 카드 선택이에요.');if(s.board[pair[0]]===s.board[pair[1]])pair.forEach(i=>matched.add(i));}if(matched.size!==12)throw Error('모든 짝을 찾아야 보상을 받아요.');score=data.moves.length;reward=Math.max(160,400-(score-6)*15);}
if(s.game==='sort'){const answers=data.answers;if(!Array.isArray(answers)||answers.length>20||answers.some(x=>!Number.isInteger(x)||x<0||x>3))throw Error('게임 결과를 확인할 수 없어요.');if(answers.length<20&&elapsed<29500)throw Error('분류 시간이 아직 남아 있어요.');score=answers.reduce((n,a,i)=>n+(a===((s.seed*13+i*7+Math.floor(i/3))%4)?1:0),0);reward=Math.max(80,80+score*20-(answers.length-score)*8);}
p.coins+=reward;p.games++;p.earned+=reward;p.best[s.game]=s.game==='memory'?(!p.best.memory?score:Math.min(p.best.memory,score)):Math.max(p.best[s.game],score);result={reward,score,game:s.game};p.session=null;
}else throw Error('알 수 없는 요청이에요.');return result;}
